//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace IPMS.Services.TrainSummary
{
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "tnpa_train_info_webservice_getTrainSummary_wsd_Binder", Namespace = "http://TFRDWINWMISA8.inter.transnet.net/tnpa_train_info/webservice/getTrainSummar" +
        "y_wsd")]
    public partial class getTrainSummary_wsd : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback getTrainSummaryOperationCompleted;

        private bool useDefaultCredentialsSetExplicitly;

        /// <remarks/>
        public getTrainSummary_wsd()
        {
            this.Url = global::IPMS.Services.Properties.Settings.Default.WebServiceConsoleApplication_TrainSummary_getTrainSummary_wsd;
            if ((this.IsLocalFileSystemWebService(this.Url) == true))
            {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else
            {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }

        public new string Url
        {
            get
            {
                return base.Url;
            }
            set
            {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true)
                            && (this.useDefaultCredentialsSetExplicitly == false))
                            && (this.IsLocalFileSystemWebService(value) == false)))
                {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }

        public new bool UseDefaultCredentials
        {
            get
            {
                return base.UseDefaultCredentials;
            }
            set
            {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }

        /// <remarks/>
        public event getTrainSummaryCompletedEventHandler getTrainSummaryCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("tnpa_train_info_webservice_getTrainSummary_wsd_Binder_getTrainSummary", RequestNamespace = "http://TFRDWINWMISA8.inter.transnet.net/tnpa_train_info/webservice/getTrainSummar" +
            "y_wsd", ResponseNamespace = "http://TFRDWINWMISA8.inter.transnet.net/tnpa_train_info/webservice/getTrainSummar" +
            "y_wsd", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("TRAIN_SUMMARY", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public TRAIN_SUMMARY[] getTrainSummary([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)] string FRM_DATE, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)] string TO_DATE)
        {
            object[] results = this.Invoke("getTrainSummary", new object[] {
                        FRM_DATE,
                        TO_DATE});
            return ((TRAIN_SUMMARY[])(results[0]));
        }

        /// <remarks/>
        public void getTrainSummaryAsync(string FRM_DATE, string TO_DATE)
        {
            this.getTrainSummaryAsync(FRM_DATE, TO_DATE, null);
        }

        /// <remarks/>
        public void getTrainSummaryAsync(string FRM_DATE, string TO_DATE, object userState)
        {
            if ((this.getTrainSummaryOperationCompleted == null))
            {
                this.getTrainSummaryOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTrainSummaryOperationCompleted);
            }
            this.InvokeAsync("getTrainSummary", new object[] {
                        FRM_DATE,
                        TO_DATE}, this.getTrainSummaryOperationCompleted, userState);
        }

        private void OngetTrainSummaryOperationCompleted(object arg)
        {
            if ((this.getTrainSummaryCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getTrainSummaryCompleted(this, new getTrainSummaryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }

        private bool IsLocalFileSystemWebService(string url)
        {
            if (((url == null)
                        || (url == string.Empty)))
            {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024)
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0)))
            {
                return true;
            }
            return false;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://TFRDWINWMISA8.inter.transnet.net/tnpa_train_info/webservice/getTrainSummar" +
        "y_wsd")]
    public partial class TRAIN_SUMMARY
    {

        private string bUSINESS_UNITField;

        private string cORRIDOR_NAMEField;

        private string sECTION_DESCField;

        private string pLAN_TYPEField;

        private string tRAIN_ROUTEField;

        private string tRAIN_NUMBERField;

        private string cATEGORY_DESCField;

        private string oRIGIN_DEPART_FROM_PLACEField;

        private string dEPART_TO_PLACEField;

        private string sCHEDULED_DEPART_DATE_TIMEField;

        private string sCHEDULED_ARRIVAL_DATE_TIMEField;

        private string rEMARKSField;

        private string lOADField;

        private string lOCO_QUANTITYField;

        private string lOCO_TYPEField;

        private string pLANNED_TONNAGEField;

        private string nWB_REF_NUMBERField;

        private string tRAIN_TYPEField;

        private string sCHEDULE_TYPEField;

        private string oUTBOUND_INBOUND_INDICATORField;

        private string aCTUAL_DEPART_DATE_TIMEField;

        private string aCTUAL_ARRIVE_DATE_TIMEField;

        private string tOTAL_WAGONSField;

        private string aCTUAL_TRAIN_MASSField;

        private string sTATUSField;

        private string dELAY_REASONField;

        private string eTAField;

        private string cANCELLATION_REF_NUMBERField;

        private string cANCELLATION_REASONField;

        private string sTAGED_REF_NUMBERField;

        private string sTAGED_REASONField;

        private string uPDATE_DATETIMEField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string BUSINESS_UNIT
        {
            get
            {
                return this.bUSINESS_UNITField;
            }
            set
            {
                this.bUSINESS_UNITField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string CORRIDOR_NAME
        {
            get
            {
                return this.cORRIDOR_NAMEField;
            }
            set
            {
                this.cORRIDOR_NAMEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string SECTION_DESC
        {
            get
            {
                return this.sECTION_DESCField;
            }
            set
            {
                this.sECTION_DESCField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string PLAN_TYPE
        {
            get
            {
                return this.pLAN_TYPEField;
            }
            set
            {
                this.pLAN_TYPEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string TRAIN_ROUTE
        {
            get
            {
                return this.tRAIN_ROUTEField;
            }
            set
            {
                this.tRAIN_ROUTEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string TRAIN_NUMBER
        {
            get
            {
                return this.tRAIN_NUMBERField;
            }
            set
            {
                this.tRAIN_NUMBERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string CATEGORY_DESC
        {
            get
            {
                return this.cATEGORY_DESCField;
            }
            set
            {
                this.cATEGORY_DESCField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string ORIGIN_DEPART_FROM_PLACE
        {
            get
            {
                return this.oRIGIN_DEPART_FROM_PLACEField;
            }
            set
            {
                this.oRIGIN_DEPART_FROM_PLACEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string DEPART_TO_PLACE
        {
            get
            {
                return this.dEPART_TO_PLACEField;
            }
            set
            {
                this.dEPART_TO_PLACEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string SCHEDULED_DEPART_DATE_TIME
        {
            get
            {
                return this.sCHEDULED_DEPART_DATE_TIMEField;
            }
            set
            {
                this.sCHEDULED_DEPART_DATE_TIMEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string SCHEDULED_ARRIVAL_DATE_TIME
        {
            get
            {
                return this.sCHEDULED_ARRIVAL_DATE_TIMEField;
            }
            set
            {
                this.sCHEDULED_ARRIVAL_DATE_TIMEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string REMARKS
        {
            get
            {
                return this.rEMARKSField;
            }
            set
            {
                this.rEMARKSField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string LOAD
        {
            get
            {
                return this.lOADField;
            }
            set
            {
                this.lOADField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string LOCO_QUANTITY
        {
            get
            {
                return this.lOCO_QUANTITYField;
            }
            set
            {
                this.lOCO_QUANTITYField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string LOCO_TYPE
        {
            get
            {
                return this.lOCO_TYPEField;
            }
            set
            {
                this.lOCO_TYPEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string PLANNED_TONNAGE
        {
            get
            {
                return this.pLANNED_TONNAGEField;
            }
            set
            {
                this.pLANNED_TONNAGEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string NWB_REF_NUMBER
        {
            get
            {
                return this.nWB_REF_NUMBERField;
            }
            set
            {
                this.nWB_REF_NUMBERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string TRAIN_TYPE
        {
            get
            {
                return this.tRAIN_TYPEField;
            }
            set
            {
                this.tRAIN_TYPEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string SCHEDULE_TYPE
        {
            get
            {
                return this.sCHEDULE_TYPEField;
            }
            set
            {
                this.sCHEDULE_TYPEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string OUTBOUND_INBOUND_INDICATOR
        {
            get
            {
                return this.oUTBOUND_INBOUND_INDICATORField;
            }
            set
            {
                this.oUTBOUND_INBOUND_INDICATORField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string ACTUAL_DEPART_DATE_TIME
        {
            get
            {
                return this.aCTUAL_DEPART_DATE_TIMEField;
            }
            set
            {
                this.aCTUAL_DEPART_DATE_TIMEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string ACTUAL_ARRIVE_DATE_TIME
        {
            get
            {
                return this.aCTUAL_ARRIVE_DATE_TIMEField;
            }
            set
            {
                this.aCTUAL_ARRIVE_DATE_TIMEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string TOTAL_WAGONS
        {
            get
            {
                return this.tOTAL_WAGONSField;
            }
            set
            {
                this.tOTAL_WAGONSField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string ACTUAL_TRAIN_MASS
        {
            get
            {
                return this.aCTUAL_TRAIN_MASSField;
            }
            set
            {
                this.aCTUAL_TRAIN_MASSField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string STATUS
        {
            get
            {
                return this.sTATUSField;
            }
            set
            {
                this.sTATUSField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string DELAY_REASON
        {
            get
            {
                return this.dELAY_REASONField;
            }
            set
            {
                this.dELAY_REASONField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string ETA
        {
            get
            {
                return this.eTAField;
            }
            set
            {
                this.eTAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string CANCELLATION_REF_NUMBER
        {
            get
            {
                return this.cANCELLATION_REF_NUMBERField;
            }
            set
            {
                this.cANCELLATION_REF_NUMBERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string CANCELLATION_REASON
        {
            get
            {
                return this.cANCELLATION_REASONField;
            }
            set
            {
                this.cANCELLATION_REASONField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string STAGED_REF_NUMBER
        {
            get
            {
                return this.sTAGED_REF_NUMBERField;
            }
            set
            {
                this.sTAGED_REF_NUMBERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string STAGED_REASON
        {
            get
            {
                return this.sTAGED_REASONField;
            }
            set
            {
                this.sTAGED_REASONField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string UPDATE_DATETIME
        {
            get
            {
                return this.uPDATE_DATETIMEField;
            }
            set
            {
                this.uPDATE_DATETIMEField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getTrainSummaryCompletedEventHandler(object sender, getTrainSummaryCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getTrainSummaryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal getTrainSummaryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public TRAIN_SUMMARY[] Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((TRAIN_SUMMARY[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591