//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPMS.Services.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://sidgw.lloydslistintelligence.com/sidgw/services/SidDBRequest")]
        public string IPMS_Services_LloydsSOAPForVesselRegistration_SidDBRequestService {
            get {
                return ((string)(this["IPMS_Services_LloydsSOAPForVesselRegistration_SidDBRequestService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://TFRDWINWMISA8.inter.transnet.net:5555/ws/tnpa_train_info.webservice:getTra" +
            "inSummary_wsd/tnpa_train_info_webservice_getTrainSummary_wsd_Port")]
        public string WebServiceConsoleApplication_TrainSummary_getTrainSummary_wsd {
            get {
                return ((string)(this["WebServiceConsoleApplication_TrainSummary_getTrainSummary_wsd"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://TFRDWINWMISA8.inter.transnet.net:5555/ws/tnpa_train_info.webservice:getWag" +
            "onDetails_wsd/tnpa_train_info_webservice_getWagonDetails_wsd_Port")]
        public string IPMS_Services_TfrService_getWagonDetails_wsd {
            get {
                return ((string)(this["IPMS_Services_TfrService_getWagonDetails_wsd"]));
            }
        }
    }
}
