//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace IPMS.Services.TfrService
{
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "tnpa_train_info_webservice_getWagonDetails_wsd_Binder", Namespace = "http://TFRDWINWMISA8.inter.transnet.net/tnpa_train_info/webservice/getWagonDetail" +
        "s_wsd")]
    public partial class getWagonDetails_wsd : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback getWagonDetailsOperationCompleted;

        private bool useDefaultCredentialsSetExplicitly;

        /// <remarks/>
        public getWagonDetails_wsd()
        {
            this.Url = global::IPMS.Services.Properties.Settings.Default.IPMS_Services_TfrService_getWagonDetails_wsd;
            if ((this.IsLocalFileSystemWebService(this.Url) == true))
            {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else
            {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }

        public new string Url
        {
            get
            {
                return base.Url;
            }
            set
            {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true)
                            && (this.useDefaultCredentialsSetExplicitly == false))
                            && (this.IsLocalFileSystemWebService(value) == false)))
                {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }

        public new bool UseDefaultCredentials
        {
            get
            {
                return base.UseDefaultCredentials;
            }
            set
            {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }

        /// <remarks/>
        public event getWagonDetailsCompletedEventHandler getWagonDetailsCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("tnpa_train_info_webservice_getWagonDetails_wsd_Binder_getWagonDetails", RequestNamespace = "http://TFRDWINWMISA8.inter.transnet.net/tnpa_train_info/webservice/getWagonDetail" +
            "s_wsd", ResponseNamespace = "http://TFRDWINWMISA8.inter.transnet.net/tnpa_train_info/webservice/getWagonDetail" +
            "s_wsd", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("WAGON_DETAILS", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public WAGON_DETAILS[] getWagonDetails([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)] string TRAIN_NO, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)] string TRAIN_ORIGIN, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)] string ORIGIN_DATE)
        {
            object[] results = this.Invoke("getWagonDetails", new object[] {
                        TRAIN_NO,
                        TRAIN_ORIGIN,
                        ORIGIN_DATE});
            return ((WAGON_DETAILS[])(results[0]));
        }

        /// <remarks/>
        public void getWagonDetailsAsync(string TRAIN_NO, string TRAIN_ORIGIN, string ORIGIN_DATE)
        {
            this.getWagonDetailsAsync(TRAIN_NO, TRAIN_ORIGIN, ORIGIN_DATE, null);
        }

        /// <remarks/>
        public void getWagonDetailsAsync(string TRAIN_NO, string TRAIN_ORIGIN, string ORIGIN_DATE, object userState)
        {
            if ((this.getWagonDetailsOperationCompleted == null))
            {
                this.getWagonDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetWagonDetailsOperationCompleted);
            }
            this.InvokeAsync("getWagonDetails", new object[] {
                        TRAIN_NO,
                        TRAIN_ORIGIN,
                        ORIGIN_DATE}, this.getWagonDetailsOperationCompleted, userState);
        }

        private void OngetWagonDetailsOperationCompleted(object arg)
        {
            if ((this.getWagonDetailsCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getWagonDetailsCompleted(this, new getWagonDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }

        private bool IsLocalFileSystemWebService(string url)
        {
            if (((url == null)
                        || (url == string.Empty)))
            {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024)
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0)))
            {
                return true;
            }
            return false;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://TFRDWINWMISA8.inter.transnet.net/tnpa_train_info/webservice/getWagonDetail" +
        "s_wsd")]
    public partial class WAGON_DETAILS
    {

        private string tRAIN_NOField;

        private string wAGON_NUMBERField;

        private string wAGON_TYPEField;

        private string cOMMODITYField;

        private string tONNAGEField;

        private string oRIGIN_DATEField;

        private string tRAIN_ORIGINField;

        private string uPDATE_DATETIMEField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string TRAIN_NO
        {
            get
            {
                return this.tRAIN_NOField;
            }
            set
            {
                this.tRAIN_NOField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string WAGON_NUMBER
        {
            get
            {
                return this.wAGON_NUMBERField;
            }
            set
            {
                this.wAGON_NUMBERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string WAGON_TYPE
        {
            get
            {
                return this.wAGON_TYPEField;
            }
            set
            {
                this.wAGON_TYPEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string COMMODITY
        {
            get
            {
                return this.cOMMODITYField;
            }
            set
            {
                this.cOMMODITYField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string TONNAGE
        {
            get
            {
                return this.tONNAGEField;
            }
            set
            {
                this.tONNAGEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string ORIGIN_DATE
        {
            get
            {
                return this.oRIGIN_DATEField;
            }
            set
            {
                this.oRIGIN_DATEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string TRAIN_ORIGIN
        {
            get
            {
                return this.tRAIN_ORIGINField;
            }
            set
            {
                this.tRAIN_ORIGINField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string UPDATE_DATETIME
        {
            get
            {
                return this.uPDATE_DATETIMEField;
            }
            set
            {
                this.uPDATE_DATETIMEField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getWagonDetailsCompletedEventHandler(object sender, getWagonDetailsCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getWagonDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal getWagonDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public WAGON_DETAILS[] Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((WAGON_DETAILS[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591