//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPNotifications.Engine.MarineOrderServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MarineOrderServiceReference.BiztalkMarineService")]
    public interface BiztalkMarineService {
        
        // CODEGEN: Generating message contract since the operation BiztalkMarineOperation is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="BiztalkMarineOperation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SAPNotifications.Engine.MarineOrderServiceReference.BiztalkMarineOperationResponse BiztalkMarineOperation(SAPNotifications.Engine.MarineOrderServiceReference.BiztalkMarineOperationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="BiztalkMarineOperation", ReplyAction="*")]
        System.Threading.Tasks.Task<SAPNotifications.Engine.MarineOrderServiceReference.BiztalkMarineOperationResponse> BiztalkMarineOperationAsync(SAPNotifications.Engine.MarineOrderServiceReference.BiztalkMarineOperationRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://IPMSConnect_SAP.MarineOrder")]
    public partial class MARINEORDER : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dISTRIBUTIONCHANNELField;
        
        private string oRDERField;
        
        private string dIVISIONField;
        
        private MARINEORDERItem[] oRDERHEADERINXField;
        
        private MARINEORDERItem1[] oRDERITEMINField;
        
        private MARINEORDERItem2[] oRDERITEMSINXField;
        
        private string iTEMNOField;
        
        private string oRDERTYPEField;
        
        private int pONOField;
        
        private MARINEORDERItem3[] rETURNField;
        
        private string sALESORGANIZATIONField;
        
        private MARINEORDERItem4[] sCHEDULELINESField;
        
        private MARINEORDERItem5[] sCHEDULELINESXField;
        
        private System.DateTime cREATEDDATEField;
        
        private int rEVENUEPOSTINGIDField;
        
        private string mESSAGETYPEField;
        
        private int sAPPOSTINGIDField;
        
        private string sALESDOCUMENTField;
        
        private string sHIPTOPARTYField;
        
        private string sOLDTOPARTYField;
        
        private string zZDATEFROMField;
        
        private string zZTIMEFROMField;
        
        private string zZTIMETOField;
        
        private string zZDATETOField;
        
        private string zZDOCKTIMEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string DISTRIBUTIONCHANNEL {
            get {
                return this.dISTRIBUTIONCHANNELField;
            }
            set {
                this.dISTRIBUTIONCHANNELField = value;
                this.RaisePropertyChanged("DISTRIBUTIONCHANNEL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ORDER {
            get {
                return this.oRDERField;
            }
            set {
                this.oRDERField = value;
                this.RaisePropertyChanged("ORDER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string DIVISION {
            get {
                return this.dIVISIONField;
            }
            set {
                this.dIVISIONField = value;
                this.RaisePropertyChanged("DIVISION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public MARINEORDERItem[] ORDERHEADERINX {
            get {
                return this.oRDERHEADERINXField;
            }
            set {
                this.oRDERHEADERINXField = value;
                this.RaisePropertyChanged("ORDERHEADERINX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public MARINEORDERItem1[] ORDERITEMIN {
            get {
                return this.oRDERITEMINField;
            }
            set {
                this.oRDERITEMINField = value;
                this.RaisePropertyChanged("ORDERITEMIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public MARINEORDERItem2[] ORDERITEMSINX {
            get {
                return this.oRDERITEMSINXField;
            }
            set {
                this.oRDERITEMSINXField = value;
                this.RaisePropertyChanged("ORDERITEMSINX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string ITEMNO {
            get {
                return this.iTEMNOField;
            }
            set {
                this.iTEMNOField = value;
                this.RaisePropertyChanged("ITEMNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string ORDERTYPE {
            get {
                return this.oRDERTYPEField;
            }
            set {
                this.oRDERTYPEField = value;
                this.RaisePropertyChanged("ORDERTYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int PONO {
            get {
                return this.pONOField;
            }
            set {
                this.pONOField = value;
                this.RaisePropertyChanged("PONO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public MARINEORDERItem3[] RETURN {
            get {
                return this.rETURNField;
            }
            set {
                this.rETURNField = value;
                this.RaisePropertyChanged("RETURN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string SALESORGANIZATION {
            get {
                return this.sALESORGANIZATIONField;
            }
            set {
                this.sALESORGANIZATIONField = value;
                this.RaisePropertyChanged("SALESORGANIZATION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public MARINEORDERItem4[] SCHEDULELINES {
            get {
                return this.sCHEDULELINESField;
            }
            set {
                this.sCHEDULELINESField = value;
                this.RaisePropertyChanged("SCHEDULELINES");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public MARINEORDERItem5[] SCHEDULELINESX {
            get {
                return this.sCHEDULELINESXField;
            }
            set {
                this.sCHEDULELINESXField = value;
                this.RaisePropertyChanged("SCHEDULELINESX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=13)]
        public System.DateTime CREATEDDATE {
            get {
                return this.cREATEDDATEField;
            }
            set {
                this.cREATEDDATEField = value;
                this.RaisePropertyChanged("CREATEDDATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public int REVENUEPOSTINGID {
            get {
                return this.rEVENUEPOSTINGIDField;
            }
            set {
                this.rEVENUEPOSTINGIDField = value;
                this.RaisePropertyChanged("REVENUEPOSTINGID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string MESSAGETYPE {
            get {
                return this.mESSAGETYPEField;
            }
            set {
                this.mESSAGETYPEField = value;
                this.RaisePropertyChanged("MESSAGETYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public int SAPPOSTINGID {
            get {
                return this.sAPPOSTINGIDField;
            }
            set {
                this.sAPPOSTINGIDField = value;
                this.RaisePropertyChanged("SAPPOSTINGID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string SALESDOCUMENT {
            get {
                return this.sALESDOCUMENTField;
            }
            set {
                this.sALESDOCUMENTField = value;
                this.RaisePropertyChanged("SALESDOCUMENT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string SHIPTOPARTY {
            get {
                return this.sHIPTOPARTYField;
            }
            set {
                this.sHIPTOPARTYField = value;
                this.RaisePropertyChanged("SHIPTOPARTY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string SOLDTOPARTY {
            get {
                return this.sOLDTOPARTYField;
            }
            set {
                this.sOLDTOPARTYField = value;
                this.RaisePropertyChanged("SOLDTOPARTY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string ZZDATEFROM {
            get {
                return this.zZDATEFROMField;
            }
            set {
                this.zZDATEFROMField = value;
                this.RaisePropertyChanged("ZZDATEFROM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string ZZTIMEFROM {
            get {
                return this.zZTIMEFROMField;
            }
            set {
                this.zZTIMEFROMField = value;
                this.RaisePropertyChanged("ZZTIMEFROM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string ZZTIMETO {
            get {
                return this.zZTIMETOField;
            }
            set {
                this.zZTIMETOField = value;
                this.RaisePropertyChanged("ZZTIMETO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string ZZDATETO {
            get {
                return this.zZDATETOField;
            }
            set {
                this.zZDATETOField = value;
                this.RaisePropertyChanged("ZZDATETO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string ZZDOCKTIME {
            get {
                return this.zZDOCKTIMEField;
            }
            set {
                this.zZDOCKTIMEField = value;
                this.RaisePropertyChanged("ZZDOCKTIME");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://IPMSConnect_SAP.MarineOrder")]
    public partial class MARINEORDERItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string uPDATEFLAGField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string UPDATEFLAG {
            get {
                return this.uPDATEFLAGField;
            }
            set {
                this.uPDATEFLAGField = value;
                this.RaisePropertyChanged("UPDATEFLAG");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://IPMSConnect_SAP.MarineOrder")]
    public partial class MARINEORDERItem1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mATERIALField;
        
        private string iTMNUMBERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string MATERIAL {
            get {
                return this.mATERIALField;
            }
            set {
                this.mATERIALField = value;
                this.RaisePropertyChanged("MATERIAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ITMNUMBER {
            get {
                return this.iTMNUMBERField;
            }
            set {
                this.iTMNUMBERField = value;
                this.RaisePropertyChanged("ITMNUMBER");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://IPMSConnect_SAP.MarineOrder")]
    public partial class MARINEORDERItem2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iTMNUMBERField;
        
        private string uPDATEFLAGField;
        
        private string mATERIALField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ITMNUMBER {
            get {
                return this.iTMNUMBERField;
            }
            set {
                this.iTMNUMBERField = value;
                this.RaisePropertyChanged("ITMNUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string UPDATEFLAG {
            get {
                return this.uPDATEFLAGField;
            }
            set {
                this.uPDATEFLAGField = value;
                this.RaisePropertyChanged("UPDATEFLAG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string MATERIAL {
            get {
                return this.mATERIALField;
            }
            set {
                this.mATERIALField = value;
                this.RaisePropertyChanged("MATERIAL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://IPMSConnect_SAP.MarineOrder")]
    public partial class MARINEORDERItem3 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tYPEField;
        
        private string idField;
        
        private string nUMBERField;
        
        private string mESSAGEField;
        
        private string lOGNOField;
        
        private string lOGMSGNOField;
        
        private string mESSAGEV1Field;
        
        private string mESSAGEV2Field;
        
        private string mESSAGEV3Field;
        
        private string mESSAGEV4Field;
        
        private string pARAMETERField;
        
        private string rOWField;
        
        private string fIELDField;
        
        private string sYSTEMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
                this.RaisePropertyChanged("TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string NUMBER {
            get {
                return this.nUMBERField;
            }
            set {
                this.nUMBERField = value;
                this.RaisePropertyChanged("NUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
                this.RaisePropertyChanged("MESSAGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string LOGNO {
            get {
                return this.lOGNOField;
            }
            set {
                this.lOGNOField = value;
                this.RaisePropertyChanged("LOGNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string LOGMSGNO {
            get {
                return this.lOGMSGNOField;
            }
            set {
                this.lOGMSGNOField = value;
                this.RaisePropertyChanged("LOGMSGNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string MESSAGEV1 {
            get {
                return this.mESSAGEV1Field;
            }
            set {
                this.mESSAGEV1Field = value;
                this.RaisePropertyChanged("MESSAGEV1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string MESSAGEV2 {
            get {
                return this.mESSAGEV2Field;
            }
            set {
                this.mESSAGEV2Field = value;
                this.RaisePropertyChanged("MESSAGEV2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string MESSAGEV3 {
            get {
                return this.mESSAGEV3Field;
            }
            set {
                this.mESSAGEV3Field = value;
                this.RaisePropertyChanged("MESSAGEV3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string MESSAGEV4 {
            get {
                return this.mESSAGEV4Field;
            }
            set {
                this.mESSAGEV4Field = value;
                this.RaisePropertyChanged("MESSAGEV4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string PARAMETER {
            get {
                return this.pARAMETERField;
            }
            set {
                this.pARAMETERField = value;
                this.RaisePropertyChanged("PARAMETER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string ROW {
            get {
                return this.rOWField;
            }
            set {
                this.rOWField = value;
                this.RaisePropertyChanged("ROW");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string FIELD {
            get {
                return this.fIELDField;
            }
            set {
                this.fIELDField = value;
                this.RaisePropertyChanged("FIELD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string SYSTEM {
            get {
                return this.sYSTEMField;
            }
            set {
                this.sYSTEMField = value;
                this.RaisePropertyChanged("SYSTEM");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://IPMSConnect_SAP.MarineOrder")]
    public partial class MARINEORDERItem4 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iTMNUMBERField;
        
        private string sCHEDLINEField;
        
        private string rEQQTYField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ITMNUMBER {
            get {
                return this.iTMNUMBERField;
            }
            set {
                this.iTMNUMBERField = value;
                this.RaisePropertyChanged("ITMNUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string SCHEDLINE {
            get {
                return this.sCHEDLINEField;
            }
            set {
                this.sCHEDLINEField = value;
                this.RaisePropertyChanged("SCHEDLINE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string REQQTY {
            get {
                return this.rEQQTYField;
            }
            set {
                this.rEQQTYField = value;
                this.RaisePropertyChanged("REQQTY");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://IPMSConnect_SAP.MarineOrder")]
    public partial class MARINEORDERItem5 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iTMNUMBERField;
        
        private string sCHEDLINEField;
        
        private string uPDATEFLAGField;
        
        private string rEQDATEField;
        
        private string dATETYPEField;
        
        private string rEQTIMEField;
        
        private string rEQQTYField;
        
        private string rEQDLVBLField;
        
        private string sCHEDTYPEField;
        
        private string tPDATEField;
        
        private string mSDATEField;
        
        private string lOADDATEField;
        
        private string gIDATEField;
        
        private string mSTIMEField;
        
        private string lOADTIMEField;
        
        private string gITIMEField;
        
        private string rEFOBJTYPEField;
        
        private string rEFOBJKEYField;
        
        private string dLVDATEField;
        
        private string dLVTIMEField;
        
        private string rELTYPEField;
        
        private string pLANSCHEDTYPEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ITMNUMBER {
            get {
                return this.iTMNUMBERField;
            }
            set {
                this.iTMNUMBERField = value;
                this.RaisePropertyChanged("ITMNUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string SCHEDLINE {
            get {
                return this.sCHEDLINEField;
            }
            set {
                this.sCHEDLINEField = value;
                this.RaisePropertyChanged("SCHEDLINE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string UPDATEFLAG {
            get {
                return this.uPDATEFLAGField;
            }
            set {
                this.uPDATEFLAGField = value;
                this.RaisePropertyChanged("UPDATEFLAG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string REQDATE {
            get {
                return this.rEQDATEField;
            }
            set {
                this.rEQDATEField = value;
                this.RaisePropertyChanged("REQDATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string DATETYPE {
            get {
                return this.dATETYPEField;
            }
            set {
                this.dATETYPEField = value;
                this.RaisePropertyChanged("DATETYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string REQTIME {
            get {
                return this.rEQTIMEField;
            }
            set {
                this.rEQTIMEField = value;
                this.RaisePropertyChanged("REQTIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string REQQTY {
            get {
                return this.rEQQTYField;
            }
            set {
                this.rEQQTYField = value;
                this.RaisePropertyChanged("REQQTY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string REQDLVBL {
            get {
                return this.rEQDLVBLField;
            }
            set {
                this.rEQDLVBLField = value;
                this.RaisePropertyChanged("REQDLVBL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string SCHEDTYPE {
            get {
                return this.sCHEDTYPEField;
            }
            set {
                this.sCHEDTYPEField = value;
                this.RaisePropertyChanged("SCHEDTYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string TPDATE {
            get {
                return this.tPDATEField;
            }
            set {
                this.tPDATEField = value;
                this.RaisePropertyChanged("TPDATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string MSDATE {
            get {
                return this.mSDATEField;
            }
            set {
                this.mSDATEField = value;
                this.RaisePropertyChanged("MSDATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string LOADDATE {
            get {
                return this.lOADDATEField;
            }
            set {
                this.lOADDATEField = value;
                this.RaisePropertyChanged("LOADDATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string GIDATE {
            get {
                return this.gIDATEField;
            }
            set {
                this.gIDATEField = value;
                this.RaisePropertyChanged("GIDATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string MSTIME {
            get {
                return this.mSTIMEField;
            }
            set {
                this.mSTIMEField = value;
                this.RaisePropertyChanged("MSTIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string LOADTIME {
            get {
                return this.lOADTIMEField;
            }
            set {
                this.lOADTIMEField = value;
                this.RaisePropertyChanged("LOADTIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string GITIME {
            get {
                return this.gITIMEField;
            }
            set {
                this.gITIMEField = value;
                this.RaisePropertyChanged("GITIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string REFOBJTYPE {
            get {
                return this.rEFOBJTYPEField;
            }
            set {
                this.rEFOBJTYPEField = value;
                this.RaisePropertyChanged("REFOBJTYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string REFOBJKEY {
            get {
                return this.rEFOBJKEYField;
            }
            set {
                this.rEFOBJKEYField = value;
                this.RaisePropertyChanged("REFOBJKEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string DLVDATE {
            get {
                return this.dLVDATEField;
            }
            set {
                this.dLVDATEField = value;
                this.RaisePropertyChanged("DLVDATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string DLVTIME {
            get {
                return this.dLVTIMEField;
            }
            set {
                this.dLVTIMEField = value;
                this.RaisePropertyChanged("DLVTIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string RELTYPE {
            get {
                return this.rELTYPEField;
            }
            set {
                this.rELTYPEField = value;
                this.RaisePropertyChanged("RELTYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string PLANSCHEDTYPE {
            get {
                return this.pLANSCHEDTYPEField;
            }
            set {
                this.pLANSCHEDTYPEField = value;
                this.RaisePropertyChanged("PLANSCHEDTYPE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://IPMSConnect_SAP.StatusMsg")]
    public partial class Status : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BiztalkMarineOperationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://IPMSConnect_SAP.MarineOrder", Order=0)]
        public SAPNotifications.Engine.MarineOrderServiceReference.MARINEORDER MARINEORDER;
        
        public BiztalkMarineOperationRequest() {
        }
        
        public BiztalkMarineOperationRequest(SAPNotifications.Engine.MarineOrderServiceReference.MARINEORDER MARINEORDER) {
            this.MARINEORDER = MARINEORDER;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BiztalkMarineOperationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://IPMSConnect_SAP.StatusMsg", Order=0)]
        public SAPNotifications.Engine.MarineOrderServiceReference.Status Status;
        
        public BiztalkMarineOperationResponse() {
        }
        
        public BiztalkMarineOperationResponse(SAPNotifications.Engine.MarineOrderServiceReference.Status Status) {
            this.Status = Status;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BiztalkMarineServiceChannel : SAPNotifications.Engine.MarineOrderServiceReference.BiztalkMarineService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BiztalkMarineServiceClient : System.ServiceModel.ClientBase<SAPNotifications.Engine.MarineOrderServiceReference.BiztalkMarineService>, SAPNotifications.Engine.MarineOrderServiceReference.BiztalkMarineService {
        
        public BiztalkMarineServiceClient() {
        }
        
        public BiztalkMarineServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BiztalkMarineServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BiztalkMarineServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BiztalkMarineServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SAPNotifications.Engine.MarineOrderServiceReference.BiztalkMarineOperationResponse SAPNotifications.Engine.MarineOrderServiceReference.BiztalkMarineService.BiztalkMarineOperation(SAPNotifications.Engine.MarineOrderServiceReference.BiztalkMarineOperationRequest request) {
            return base.Channel.BiztalkMarineOperation(request);
        }
        
        public SAPNotifications.Engine.MarineOrderServiceReference.Status BiztalkMarineOperation(SAPNotifications.Engine.MarineOrderServiceReference.MARINEORDER MARINEORDER) {
            SAPNotifications.Engine.MarineOrderServiceReference.BiztalkMarineOperationRequest inValue = new SAPNotifications.Engine.MarineOrderServiceReference.BiztalkMarineOperationRequest();
            inValue.MARINEORDER = MARINEORDER;
            SAPNotifications.Engine.MarineOrderServiceReference.BiztalkMarineOperationResponse retVal = ((SAPNotifications.Engine.MarineOrderServiceReference.BiztalkMarineService)(this)).BiztalkMarineOperation(inValue);
            return retVal.Status;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SAPNotifications.Engine.MarineOrderServiceReference.BiztalkMarineOperationResponse> SAPNotifications.Engine.MarineOrderServiceReference.BiztalkMarineService.BiztalkMarineOperationAsync(SAPNotifications.Engine.MarineOrderServiceReference.BiztalkMarineOperationRequest request) {
            return base.Channel.BiztalkMarineOperationAsync(request);
        }
        
        public System.Threading.Tasks.Task<SAPNotifications.Engine.MarineOrderServiceReference.BiztalkMarineOperationResponse> BiztalkMarineOperationAsync(SAPNotifications.Engine.MarineOrderServiceReference.MARINEORDER MARINEORDER) {
            SAPNotifications.Engine.MarineOrderServiceReference.BiztalkMarineOperationRequest inValue = new SAPNotifications.Engine.MarineOrderServiceReference.BiztalkMarineOperationRequest();
            inValue.MARINEORDER = MARINEORDER;
            return ((SAPNotifications.Engine.MarineOrderServiceReference.BiztalkMarineService)(this)).BiztalkMarineOperationAsync(inValue);
        }
    }
}
