//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace IPMS.Services.LloydsSOAPForVesselRegistration {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SidDBRequestSoapBinding", Namespace="https://sidgw.lloydslistintelligence.com/sidgw/services/SidDBRequest")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(Vector))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(SoapException))]
    public partial class SidDBRequestService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback request_dataOperationCompleted;
        
        private System.Threading.SendOrPostCallback request_data1OperationCompleted;
        
        private System.Threading.SendOrPostCallback soap_callOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SidDBRequestService() {
            this.Url = global::IPMS.Services.Properties.Settings.Default.IPMS_Services_LloydsSOAPForVesselRegistration_SidDBRequestService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event request_dataCompletedEventHandler request_dataCompleted;
        
        /// <remarks/>
        public event request_data1CompletedEventHandler request_data1Completed;
        
        /// <remarks/>
        public event soap_callCompletedEventHandler soap_callCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://soap.lmiu.com", ResponseNamespace="https://sidgw.lloydslistintelligence.com/sidgw/services/SidDBRequest")]
        [return: System.Xml.Serialization.SoapElementAttribute("request_dataReturn")]
        public string request_data(string user, string password, string function, string var1, string var2, string var3, string var4, string var5, string var6, string var7, string var8, string var9, string var10) {
            object[] results = this.Invoke("request_data", new object[] {
                        user,
                        password,
                        function,
                        var1,
                        var2,
                        var3,
                        var4,
                        var5,
                        var6,
                        var7,
                        var8,
                        var9,
                        var10});
            return ((string)(results[0]));
        }


        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName = "request_data1")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace = "http://soap.lmiu.com", ResponseNamespace = "https://sidgw.lloydslistintelligence.com/sidgw/services/SidDBRequest")]
        [return: System.Xml.Serialization.SoapElementAttribute("request_dataReturn")]
        public string request_data1(string user, string password, string function, string var1, string var2, string var3, string var4, string var5, string var6, string var7, string var8, string var9, string var10)
        {
            object[] results = this.Invoke("request_data1", new object[] {
                        user,
                        password,
                        function,
                        var1,
                        var2,
                        var3,
                        var4,
                        var5,
                        var6,
                        var7,
                        var8,
                        var9,
                        var10});
            return ((string)(results[0]));
        }


        /// <remarks/>
        public void request_dataAsync(string user, string password, string function, string var1, string var2, string var3, string var4, string var5, string var6, string var7, string var8, string var9, string var10) {
            this.request_dataAsync(user, password, function, var1, var2, var3, var4, var5, var6, var7, var8, var9, var10, null);
        }
        
        /// <remarks/>
        public void request_dataAsync(string user, string password, string function, string var1, string var2, string var3, string var4, string var5, string var6, string var7, string var8, string var9, string var10, object userState) {
            if ((this.request_dataOperationCompleted == null)) {
                this.request_dataOperationCompleted = new System.Threading.SendOrPostCallback(this.Onrequest_dataOperationCompleted);
            }
            this.InvokeAsync("request_data", new object[] {
                        user,
                        password,
                        function,
                        var1,
                        var2,
                        var3,
                        var4,
                        var5,
                        var6,
                        var7,
                        var8,
                        var9,
                        var10}, this.request_dataOperationCompleted, userState);
        }
        
        private void Onrequest_dataOperationCompleted(object arg) {
            if ((this.request_dataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.request_dataCompleted(this, new request_dataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
           
        /// <remarks/>
        public void request_data1Async(string user, string password, string function, string var1, string var2, string var3, string var4, string var5, string var6, string var7, string var8, string var9, string var10) {
            this.request_data1Async(user, password, function, var1, var2, var3, var4, var5, var6, var7, var8, var9, var10, null);
        }
        
        /// <remarks/>
        public void request_data1Async(string user, string password, string function, string var1, string var2, string var3, string var4, string var5, string var6, string var7, string var8, string var9, string var10, object userState) {
            if ((this.request_data1OperationCompleted == null)) {
                this.request_data1OperationCompleted = new System.Threading.SendOrPostCallback(this.Onrequest_data1OperationCompleted);
            }
            this.InvokeAsync("request_data1", new object[] {
                        user,
                        password,
                        function,
                        var1,
                        var2,
                        var3,
                        var4,
                        var5,
                        var6,
                        var7,
                        var8,
                        var9,
                        var10}, this.request_data1OperationCompleted, userState);
        }
        
        private void Onrequest_data1OperationCompleted(object arg) {
            if ((this.request_data1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.request_data1Completed(this, new request_data1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://soap.lmiu.com", ResponseNamespace="https://sidgw.lloydslistintelligence.com/sidgw/services/SidDBRequest")]
        [return: System.Xml.Serialization.SoapElementAttribute("soap_callReturn")]
        public object[] soap_call(string user, string password, string function, string var1, string var2, string var3, string var4, string var5, string var6, string var7, string var8, string var9, string var10) {
            object[] results = this.Invoke("soap_call", new object[] {
                        user,
                        password,
                        function,
                        var1,
                        var2,
                        var3,
                        var4,
                        var5,
                        var6,
                        var7,
                        var8,
                        var9,
                        var10});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void soap_callAsync(string user, string password, string function, string var1, string var2, string var3, string var4, string var5, string var6, string var7, string var8, string var9, string var10) {
            this.soap_callAsync(user, password, function, var1, var2, var3, var4, var5, var6, var7, var8, var9, var10, null);
        }
        
        /// <remarks/>
        public void soap_callAsync(string user, string password, string function, string var1, string var2, string var3, string var4, string var5, string var6, string var7, string var8, string var9, string var10, object userState) {
            if ((this.soap_callOperationCompleted == null)) {
                this.soap_callOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsoap_callOperationCompleted);
            }
            this.InvokeAsync("soap_call", new object[] {
                        user,
                        password,
                        function,
                        var1,
                        var2,
                        var3,
                        var4,
                        var5,
                        var6,
                        var7,
                        var8,
                        var9,
                        var10}, this.soap_callOperationCompleted, userState);
        }
        
        private void Onsoap_callOperationCompleted(object arg) {
            if ((this.soap_callCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.soap_callCompleted(this, new soap_callCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://xml.apache.org/xml-soap")]
    public partial class Vector {
        
        private object[] itemField;
        
        /// <remarks/>
        public object[] item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="https://sidgw.lloydslistintelligence.com/sidgw/services/SidDBRequest")]
    public partial class SoapException {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void request_dataCompletedEventHandler(object sender, request_dataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class request_dataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal request_dataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void request_data1CompletedEventHandler(object sender, request_data1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class request_data1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal request_data1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void soap_callCompletedEventHandler(object sender, soap_callCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class soap_callCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal soap_callCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591