//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPNotification.Service.VesselCreateServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VesselCreateServiceReference.BiztalkVesselCreateService")]
    public interface BiztalkVesselCreateService {
        
        // CODEGEN: Generating message contract since the operation BiztalkVesselCreateOperation is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="BiztalkVesselCreateOperation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SAPNotification.Service.VesselCreateServiceReference.BiztalkVesselCreateOperationResponse BiztalkVesselCreateOperation(SAPNotification.Service.VesselCreateServiceReference.BiztalkVesselCreateOperationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="BiztalkVesselCreateOperation", ReplyAction="*")]
        System.Threading.Tasks.Task<SAPNotification.Service.VesselCreateServiceReference.BiztalkVesselCreateOperationResponse> BiztalkVesselCreateOperationAsync(SAPNotification.Service.VesselCreateServiceReference.BiztalkVesselCreateOperationRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://IPMSConnect_SAP.VesselCreate")]
    public partial class VesselCreate : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iCALLSIGNField;
        
        private string iCITYField;
        
        private string iCOUNTRYField;
        
        private System.DateTime iDATEField;
        
        private string iIMOField;
        
        private string iLENGTHField;
        
        private string iPOSTALField;
        
        private string iTONNAGEField;
        
        private string iVESINDField;
        
        private string iVESNAMEField;
        
        private string iVESTYPEField;
        
        private VesselCreateItem[] mESSTABField;
        
        private string eNUMBERField;
        
        private int sUBRCField;
        
        private int sAPPOSTINGIDField;
        
        private string mESSAGETYPEField;
        
        private int vESSELIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ICALLSIGN {
            get {
                return this.iCALLSIGNField;
            }
            set {
                this.iCALLSIGNField = value;
                this.RaisePropertyChanged("ICALLSIGN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ICITY {
            get {
                return this.iCITYField;
            }
            set {
                this.iCITYField = value;
                this.RaisePropertyChanged("ICITY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ICOUNTRY {
            get {
                return this.iCOUNTRYField;
            }
            set {
                this.iCOUNTRYField = value;
                this.RaisePropertyChanged("ICOUNTRY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=3)]
        public System.DateTime IDATE {
            get {
                return this.iDATEField;
            }
            set {
                this.iDATEField = value;
                this.RaisePropertyChanged("IDATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string IIMO {
            get {
                return this.iIMOField;
            }
            set {
                this.iIMOField = value;
                this.RaisePropertyChanged("IIMO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string ILENGTH {
            get {
                return this.iLENGTHField;
            }
            set {
                this.iLENGTHField = value;
                this.RaisePropertyChanged("ILENGTH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string IPOSTAL {
            get {
                return this.iPOSTALField;
            }
            set {
                this.iPOSTALField = value;
                this.RaisePropertyChanged("IPOSTAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string ITONNAGE {
            get {
                return this.iTONNAGEField;
            }
            set {
                this.iTONNAGEField = value;
                this.RaisePropertyChanged("ITONNAGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string IVESIND {
            get {
                return this.iVESINDField;
            }
            set {
                this.iVESINDField = value;
                this.RaisePropertyChanged("IVESIND");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string IVESNAME {
            get {
                return this.iVESNAMEField;
            }
            set {
                this.iVESNAMEField = value;
                this.RaisePropertyChanged("IVESNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string IVESTYPE {
            get {
                return this.iVESTYPEField;
            }
            set {
                this.iVESTYPEField = value;
                this.RaisePropertyChanged("IVESTYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public VesselCreateItem[] MESSTAB {
            get {
                return this.mESSTABField;
            }
            set {
                this.mESSTABField = value;
                this.RaisePropertyChanged("MESSTAB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string ENUMBER {
            get {
                return this.eNUMBERField;
            }
            set {
                this.eNUMBERField = value;
                this.RaisePropertyChanged("ENUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public int SUBRC {
            get {
                return this.sUBRCField;
            }
            set {
                this.sUBRCField = value;
                this.RaisePropertyChanged("SUBRC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public int SAPPOSTINGID {
            get {
                return this.sAPPOSTINGIDField;
            }
            set {
                this.sAPPOSTINGIDField = value;
                this.RaisePropertyChanged("SAPPOSTINGID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string MESSAGETYPE {
            get {
                return this.mESSAGETYPEField;
            }
            set {
                this.mESSAGETYPEField = value;
                this.RaisePropertyChanged("MESSAGETYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public int VESSELID {
            get {
                return this.vESSELIDField;
            }
            set {
                this.vESSELIDField = value;
                this.RaisePropertyChanged("VESSELID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://IPMSConnect_SAP.VesselCreate")]
    public partial class VesselCreateItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tCODEField;
        
        private string dYNAMEField;
        
        private string dYNUMBField;
        
        private string mSGTYPField;
        
        private string mSGSPRAField;
        
        private string mSGIDField;
        
        private string mSGNRField;
        
        private string mSGV1Field;
        
        private string mSGV2Field;
        
        private string mSGV3Field;
        
        private string mSGV4Field;
        
        private string eNVField;
        
        private string fLDNAMEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TCODE {
            get {
                return this.tCODEField;
            }
            set {
                this.tCODEField = value;
                this.RaisePropertyChanged("TCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string DYNAME {
            get {
                return this.dYNAMEField;
            }
            set {
                this.dYNAMEField = value;
                this.RaisePropertyChanged("DYNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string DYNUMB {
            get {
                return this.dYNUMBField;
            }
            set {
                this.dYNUMBField = value;
                this.RaisePropertyChanged("DYNUMB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string MSGTYP {
            get {
                return this.mSGTYPField;
            }
            set {
                this.mSGTYPField = value;
                this.RaisePropertyChanged("MSGTYP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string MSGSPRA {
            get {
                return this.mSGSPRAField;
            }
            set {
                this.mSGSPRAField = value;
                this.RaisePropertyChanged("MSGSPRA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string MSGID {
            get {
                return this.mSGIDField;
            }
            set {
                this.mSGIDField = value;
                this.RaisePropertyChanged("MSGID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string MSGNR {
            get {
                return this.mSGNRField;
            }
            set {
                this.mSGNRField = value;
                this.RaisePropertyChanged("MSGNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string MSGV1 {
            get {
                return this.mSGV1Field;
            }
            set {
                this.mSGV1Field = value;
                this.RaisePropertyChanged("MSGV1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string MSGV2 {
            get {
                return this.mSGV2Field;
            }
            set {
                this.mSGV2Field = value;
                this.RaisePropertyChanged("MSGV2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string MSGV3 {
            get {
                return this.mSGV3Field;
            }
            set {
                this.mSGV3Field = value;
                this.RaisePropertyChanged("MSGV3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string MSGV4 {
            get {
                return this.mSGV4Field;
            }
            set {
                this.mSGV4Field = value;
                this.RaisePropertyChanged("MSGV4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string ENV {
            get {
                return this.eNVField;
            }
            set {
                this.eNVField = value;
                this.RaisePropertyChanged("ENV");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string FLDNAME {
            get {
                return this.fLDNAMEField;
            }
            set {
                this.fLDNAMEField = value;
                this.RaisePropertyChanged("FLDNAME");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://IPMSConnect_SAP.StatusMsg")]
    public partial class Status : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BiztalkVesselCreateOperationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://IPMSConnect_SAP.VesselCreate", Order=0)]
        public SAPNotification.Service.VesselCreateServiceReference.VesselCreate VesselCreate;
        
        public BiztalkVesselCreateOperationRequest() {
        }
        
        public BiztalkVesselCreateOperationRequest(SAPNotification.Service.VesselCreateServiceReference.VesselCreate VesselCreate) {
            this.VesselCreate = VesselCreate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BiztalkVesselCreateOperationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://IPMSConnect_SAP.StatusMsg", Order=0)]
        public SAPNotification.Service.VesselCreateServiceReference.Status Status;
        
        public BiztalkVesselCreateOperationResponse() {
        }
        
        public BiztalkVesselCreateOperationResponse(SAPNotification.Service.VesselCreateServiceReference.Status Status) {
            this.Status = Status;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BiztalkVesselCreateServiceChannel : SAPNotification.Service.VesselCreateServiceReference.BiztalkVesselCreateService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BiztalkVesselCreateServiceClient : System.ServiceModel.ClientBase<SAPNotification.Service.VesselCreateServiceReference.BiztalkVesselCreateService>, SAPNotification.Service.VesselCreateServiceReference.BiztalkVesselCreateService {
        
        public BiztalkVesselCreateServiceClient() {
        }
        
        public BiztalkVesselCreateServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BiztalkVesselCreateServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BiztalkVesselCreateServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BiztalkVesselCreateServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SAPNotification.Service.VesselCreateServiceReference.BiztalkVesselCreateOperationResponse SAPNotification.Service.VesselCreateServiceReference.BiztalkVesselCreateService.BiztalkVesselCreateOperation(SAPNotification.Service.VesselCreateServiceReference.BiztalkVesselCreateOperationRequest request) {
            return base.Channel.BiztalkVesselCreateOperation(request);
        }
        
        public SAPNotification.Service.VesselCreateServiceReference.Status BiztalkVesselCreateOperation(SAPNotification.Service.VesselCreateServiceReference.VesselCreate VesselCreate) {
            SAPNotification.Service.VesselCreateServiceReference.BiztalkVesselCreateOperationRequest inValue = new SAPNotification.Service.VesselCreateServiceReference.BiztalkVesselCreateOperationRequest();
            inValue.VesselCreate = VesselCreate;
            SAPNotification.Service.VesselCreateServiceReference.BiztalkVesselCreateOperationResponse retVal = ((SAPNotification.Service.VesselCreateServiceReference.BiztalkVesselCreateService)(this)).BiztalkVesselCreateOperation(inValue);
            return retVal.Status;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SAPNotification.Service.VesselCreateServiceReference.BiztalkVesselCreateOperationResponse> SAPNotification.Service.VesselCreateServiceReference.BiztalkVesselCreateService.BiztalkVesselCreateOperationAsync(SAPNotification.Service.VesselCreateServiceReference.BiztalkVesselCreateOperationRequest request) {
            return base.Channel.BiztalkVesselCreateOperationAsync(request);
        }
        
        public System.Threading.Tasks.Task<SAPNotification.Service.VesselCreateServiceReference.BiztalkVesselCreateOperationResponse> BiztalkVesselCreateOperationAsync(SAPNotification.Service.VesselCreateServiceReference.VesselCreate VesselCreate) {
            SAPNotification.Service.VesselCreateServiceReference.BiztalkVesselCreateOperationRequest inValue = new SAPNotification.Service.VesselCreateServiceReference.BiztalkVesselCreateOperationRequest();
            inValue.VesselCreate = VesselCreate;
            return ((SAPNotification.Service.VesselCreateServiceReference.BiztalkVesselCreateService)(this)).BiztalkVesselCreateOperationAsync(inValue);
        }
    }
}
