//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPNotifications.Engine.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.BiztalkArrivalService")]
    public interface BiztalkArrivalService {
        
        // CODEGEN: Generating message contract since the operation BiztalkArrivalOperation is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="BiztalkArrivalOperation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SAPNotifications.Engine.ServiceReference2.BiztalkArrivalOperationResponse BiztalkArrivalOperation(SAPNotifications.Engine.ServiceReference2.BiztalkArrivalOperationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="BiztalkArrivalOperation", ReplyAction="*")]
        System.Threading.Tasks.Task<SAPNotifications.Engine.ServiceReference2.BiztalkArrivalOperationResponse> BiztalkArrivalOperationAsync(SAPNotifications.Engine.ServiceReference2.BiztalkArrivalOperationRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://IPMSConnect_SAP.SAPArrivalObj")]
    public partial class SAPArrival : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int aRRNOField;
        
        private string cODEField;
        
        private System.DateTime eDAField;
        
        private string kUNNRField;
        
        private string pORTCALLField;
        
        private string pORTORIGINField;
        
        private string vKORGField;
        
        private string vOYINField;
        
        private string vOYOUTField;
        
        private string zZBERTHField;
        
        private string vCNField;
        
        private System.DateTime eDDField;
        
        private int sAPPostingIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int ARRNO {
            get {
                return this.aRRNOField;
            }
            set {
                this.aRRNOField = value;
                this.RaisePropertyChanged("ARRNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CODE {
            get {
                return this.cODEField;
            }
            set {
                this.cODEField = value;
                this.RaisePropertyChanged("CODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=2)]
        public System.DateTime EDA {
            get {
                return this.eDAField;
            }
            set {
                this.eDAField = value;
                this.RaisePropertyChanged("EDA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string KUNNR {
            get {
                return this.kUNNRField;
            }
            set {
                this.kUNNRField = value;
                this.RaisePropertyChanged("KUNNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string PORTCALL {
            get {
                return this.pORTCALLField;
            }
            set {
                this.pORTCALLField = value;
                this.RaisePropertyChanged("PORTCALL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string PORTORIGIN {
            get {
                return this.pORTORIGINField;
            }
            set {
                this.pORTORIGINField = value;
                this.RaisePropertyChanged("PORTORIGIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string VKORG {
            get {
                return this.vKORGField;
            }
            set {
                this.vKORGField = value;
                this.RaisePropertyChanged("VKORG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string VOYIN {
            get {
                return this.vOYINField;
            }
            set {
                this.vOYINField = value;
                this.RaisePropertyChanged("VOYIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string VOYOUT {
            get {
                return this.vOYOUTField;
            }
            set {
                this.vOYOUTField = value;
                this.RaisePropertyChanged("VOYOUT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string ZZBERTH {
            get {
                return this.zZBERTHField;
            }
            set {
                this.zZBERTHField = value;
                this.RaisePropertyChanged("ZZBERTH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string VCN {
            get {
                return this.vCNField;
            }
            set {
                this.vCNField = value;
                this.RaisePropertyChanged("VCN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=11)]
        public System.DateTime EDD {
            get {
                return this.eDDField;
            }
            set {
                this.eDDField = value;
                this.RaisePropertyChanged("EDD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public int SAPPostingID {
            get {
                return this.sAPPostingIDField;
            }
            set {
                this.sAPPostingIDField = value;
                this.RaisePropertyChanged("SAPPostingID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://IPMSConnect_SAP.StatusMsg")]
    public partial class Status : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BiztalkArrivalOperationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://IPMSConnect_SAP.SAPArrivalObj", Order=0)]
        public SAPNotifications.Engine.ServiceReference2.SAPArrival SAPArrival;
        
        public BiztalkArrivalOperationRequest() {
        }
        
        public BiztalkArrivalOperationRequest(SAPNotifications.Engine.ServiceReference2.SAPArrival SAPArrival) {
            this.SAPArrival = SAPArrival;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BiztalkArrivalOperationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://IPMSConnect_SAP.StatusMsg", Order=0)]
        public SAPNotifications.Engine.ServiceReference2.Status Status;
        
        public BiztalkArrivalOperationResponse() {
        }
        
        public BiztalkArrivalOperationResponse(SAPNotifications.Engine.ServiceReference2.Status Status) {
            this.Status = Status;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BiztalkArrivalServiceChannel : SAPNotifications.Engine.ServiceReference2.BiztalkArrivalService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BiztalkArrivalServiceClient : System.ServiceModel.ClientBase<SAPNotifications.Engine.ServiceReference2.BiztalkArrivalService>, SAPNotifications.Engine.ServiceReference2.BiztalkArrivalService {
        
        public BiztalkArrivalServiceClient() {
        }
        
        public BiztalkArrivalServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BiztalkArrivalServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BiztalkArrivalServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BiztalkArrivalServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SAPNotifications.Engine.ServiceReference2.BiztalkArrivalOperationResponse SAPNotifications.Engine.ServiceReference2.BiztalkArrivalService.BiztalkArrivalOperation(SAPNotifications.Engine.ServiceReference2.BiztalkArrivalOperationRequest request) {
            return base.Channel.BiztalkArrivalOperation(request);
        }
        
        public SAPNotifications.Engine.ServiceReference2.Status BiztalkArrivalOperation(SAPNotifications.Engine.ServiceReference2.SAPArrival SAPArrival) {
            SAPNotifications.Engine.ServiceReference2.BiztalkArrivalOperationRequest inValue = new SAPNotifications.Engine.ServiceReference2.BiztalkArrivalOperationRequest();
            inValue.SAPArrival = SAPArrival;
            SAPNotifications.Engine.ServiceReference2.BiztalkArrivalOperationResponse retVal = ((SAPNotifications.Engine.ServiceReference2.BiztalkArrivalService)(this)).BiztalkArrivalOperation(inValue);
            return retVal.Status;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SAPNotifications.Engine.ServiceReference2.BiztalkArrivalOperationResponse> SAPNotifications.Engine.ServiceReference2.BiztalkArrivalService.BiztalkArrivalOperationAsync(SAPNotifications.Engine.ServiceReference2.BiztalkArrivalOperationRequest request) {
            return base.Channel.BiztalkArrivalOperationAsync(request);
        }
        
        public System.Threading.Tasks.Task<SAPNotifications.Engine.ServiceReference2.BiztalkArrivalOperationResponse> BiztalkArrivalOperationAsync(SAPNotifications.Engine.ServiceReference2.SAPArrival SAPArrival) {
            SAPNotifications.Engine.ServiceReference2.BiztalkArrivalOperationRequest inValue = new SAPNotifications.Engine.ServiceReference2.BiztalkArrivalOperationRequest();
            inValue.SAPArrival = SAPArrival;
            return ((SAPNotifications.Engine.ServiceReference2.BiztalkArrivalService)(this)).BiztalkArrivalOperationAsync(inValue);
        }
    }
}
